class Autogenerated {
  bool? status;
  Data? data;
  Autogenerated({this.status, this.data});
  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      status: json['status'],
      data: json['data'] != null ? Data.fromJson(json['data']) : null,
    );
  }
  Map<String, dynamic> toJson() {
    return {
      'status': status,
      'data': data?.toJson(),
    };
  }
}

class Data {
  List<Item>? list;
  int? total;
  Data({this.list, this.total});
  factory Data.fromJson(Map<String, dynamic> json) {
    List<Item> parsedList = [];
    if (json['list'] != null) {
      json['list'].forEach((v) {
        parsedList.add(Item.fromJson(v));
      });
    }
    return Data(
      list: parsedList,
      total: json['total'],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      'list': list?.map((v) => v.toJson()).toList(),
      'total': total,
    };
  }
}

class Item {
  String? id;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? eName;
  String? type;
  Parent? parent;
  List<double>? location;

  Item({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.name,
    this.eName,
    this.type,
    this.parent,
    this.location,
  });

  factory Item.fromJson(Map<String, dynamic> json) {
    return Item(
      id: json['id'],
      createdAt: json['createdAt'],
      updatedAt: json['updatedAt'],
      name: json['name'],
      eName: json['eName'],
      type: json['type'],
      parent: json['parent'] != null ? Parent.fromJson(json['parent']) : null,
      location: (json['location'] as List<dynamic>?)
          ?.map((e) => e as double)
          .toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
      'name': name,
      'eName': eName,
      'type': type,
      'parent': parent?.toJson(),
      'location': location,
    };
  }
}

class Parent {
  String? id;
  String? createdAt;
  String? updatedAt;
  String? name;
  String? eName;
  String? type;

  Parent({
    this.id,
    this.createdAt,
    this.updatedAt,
    this.name,
    this.eName,
    this.type,
  });

  factory Parent.fromJson(Map<String, dynamic> json) {
    return Parent(
      id: json['id'],
      createdAt: json['createdAt'],
      updatedAt: json['updatedAt'],
      name: json['name'],
      eName: json['eName'],
      type: json['type'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
      'name': name,
      'eName': eName,
      'type': type,
    };
  }
}
